# Generated by Django 3.2.9 on 2021-11-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_produto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Producto',
        ),
    ]
